[package]
name = "theomag-service"
version = "0.1.0"
authors = ["Paul Blouët <1818316+Geogi@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.18"
serde_json = "1.0.38"
serde_derive = "1.0.86"
serde = "1.0.86"
futures = "0.1.25"
env_logger = "0.6.0"
