[package]
name = "theomag-service"
version = "0.1.0"
authors = ["Paul Blouët <1818316+Geogi@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.15"
serde_json = "1.0.33"
serde_derive = "1.0.80"
serde = "1.0.80"
futures = "0.1.25"
